name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nix-flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix --option sandbox relaxed flake check -L --keep-going
